language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit -v tests/
  - ./vendor/bin/phpcs --config-set default_standard PSR2
  - ./vendor/bin/phpcs src/ tests/